baseURL = 'https://uninhm.dev/'
locale = 'en-us'
title = 'Unai Hernandez Minaberry'
theme = 'gokarna'

[params]
  avatarURL = 'https://avatars.githubusercontent.com/u/62044675'
  description = "CS, math and linguistics"
  accentColor = '#71c98b'
