baseURL = 'https://uninhm.dev/'
locale = 'en-us'
title = 'Unai Hernandez Minaberry'
theme = 'gokarna'

[params]
  avatarURL = 'https://avatars.githubusercontent.com/u/62044675'
  description = "CS, math and linguistics"
  accentColor = '#71c98b'

  customHeadHTML = '''
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/katex.min.css"
      integrity="sha384-WcoG4HRXMzYzfCgiyfrySxx90XSl2rxY5mnVY5TwtWE6KLrArNKn0T/mOgNL0Mmi"
      crossorigin="anonymous"
    >
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/katex.min.js"
      integrity="sha384-J+9dG2KMoiR9hqcFao0IBLwxt6zpcyN68IgwzsCSkbreXUjmNVRhPFTssqdSGjwQ"
      crossorigin="anonymous">
    </script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/contrib/auto-render.min.js"
      integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh"
      crossorigin="anonymous"
      onload="renderMathInElement(document.body);">
    </script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          delimiters: [
            {left: '\\[', right: '\\]', display: true},   // block
            {left: '$$', right: '$$', display: true},     // block
            {left: '\\(', right: '\\)', display: false},  // inline
          ],
          throwOnError : false
        });
      });
    </script>
    <script>
      function update(el) {
        el.classList.toggle(
          'katex-overflow',
          el.scrollWidth > el.clientWidth + 1
        );
      }

      function bind(el) {
        if (el.dataset.bound) return;
        el.dataset.bound = "1";

        update(el);

        const ro = new ResizeObserver(() => update(el));
        ro.observe(el);
      }

      const observer = new MutationObserver(() => {
        document.querySelectorAll('.katex-display').forEach(bind);
      });

      observer.observe(document.documentElement, {
        childList: true,
        subtree: true
      });
    </script>
    <style>
      .katex-display {
        overflow-x: auto;
        overflow-y: hidden;
      }

      .katex-display.katex-overflow::after {
        content: "";
        display: block;
        height: 12px;
      }
    </style>
  '''

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

  [[menu.main]]
    # Unique identifiers are required for menu entries without a name property,
    # or for menu entries which re-use a name
    # identifier = "github"
    name = "GitHub"

    # Absolute URL to external resource
    url = "https://github.com/uninhm"
    weight = 2

    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
    pre = "<span data-feather='github'></span>"
    post = ""
